name: SwiftDataSharing
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: ""

targets:

  # ─────────────────────────────────────────────
  # Main App
  # ─────────────────────────────────────────────
  SwiftDataSharing:
    type: application
    platform: iOS
    sources:
      - path: Sources/App
      - path: Sources/Shared
    entitlements:
      path: App/Resources/App.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.example.swiftdatasharing
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.swiftdatasharing
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: ShareExtension
      - target: NotesWidget

  # ─────────────────────────────────────────────
  # Share Extension
  # ─────────────────────────────────────────────
  ShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: Sources/ShareExtension
      - path: Sources/Shared
    entitlements:
      path: ShareExtension/Resources/ShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.example.swiftdatasharing
    info:
      path: ShareExtension/Resources/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareViewController
          NSExtensionActivationRule:
            NSExtensionActivationSupportsText: true
            NSExtensionActivationSupportsWebURLWithMaxCount: 1
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.swiftdatasharing.ShareExtension
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"

  # ─────────────────────────────────────────────
  # Widget Extension
  # ─────────────────────────────────────────────
  NotesWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: Sources/Widget
      - path: Sources/Shared
    entitlements:
      path: Widget/Resources/Widget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.example.swiftdatasharing
    info:
      path: Widget/Resources/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.swiftdatasharing.NotesWidget
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
